// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd8XcB9LvtInBeULY3LMZ3KIzw62PqvfY',
    appId: '1:564479639517:web:cae0708b5e76bbe725c034',
    messagingSenderId: '564479639517',
    projectId: 'chatapp-3de46',
    authDomain: 'chatapp-3de46.firebaseapp.com',
    storageBucket: 'chatapp-3de46.appspot.com',
    measurementId: 'G-RVL0P1XKYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPPXA0oZt7FxMW_mtD1Is-2Z6bK4AZDw',
    appId: '1:564479639517:android:1663ef87f303a31225c034',
    messagingSenderId: '564479639517',
    projectId: 'chatapp-3de46',
    storageBucket: 'chatapp-3de46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC6jwiQMc3FYpc9Da7uMD-piX1jjD959U',
    appId: '1:564479639517:ios:0874ba07fc8e0fd725c034',
    messagingSenderId: '564479639517',
    projectId: 'chatapp-3de46',
    storageBucket: 'chatapp-3de46.appspot.com',
    iosBundleId: 'com.example.messageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC6jwiQMc3FYpc9Da7uMD-piX1jjD959U',
    appId: '1:564479639517:ios:f2690f8daf2de5fc25c034',
    messagingSenderId: '564479639517',
    projectId: 'chatapp-3de46',
    storageBucket: 'chatapp-3de46.appspot.com',
    iosBundleId: 'com.example.messageapp.RunnerTests',
  );
}
